os:
  - linux
  - osx

env:
  - LFTP_SUPPORT=0
  - LFTP_SUPPORT=1

language: sh

install:
  - mkdir -p /tmp/vsftpd/empty
  - mkdir -p /tmp/ftp/pub
  - >
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      ./tests/vsftpd-3.0.3.debian7 tests/vsftpd.conf &
      if [ "$LFTP_SUPPORT" -eq 1 ]; then sudo apt-get install -y lftp; fi
    fi
  - >
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      ./tests/vsftpd-3.0.3.el_capitan tests/vsftpd.conf &
      if [ "$LFTP_SUPPORT" -eq 1 ]; then sudo installer -pkg tests/lftp-4.6.0-0.pkg -target /; fi
    fi

before_script:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
  - export GIT_FTP_HOST=localhost
  - export GIT_FTP_PORT=:2121
  - export GIT_FTP_ROOT=pub
  - export GIT_FTP_USER=ftp
  - export GIT_FTP_PASSWD=ftp
  #- export TEST_CASES="test_inits test_push_nothing test_file_with_unicode"

script:
  - tests/git-ftp-test.sh

after_failure:
  - cat /tmp/ftp.log
  - ls -la /tmp/ftp/pub
  - ls -la /tmp/ftp/pub/*
